repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff-check
      files: ^custom_components/
    - id: ruff-format
      files: ^custom_components/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy
      files: ^custom_components/
