repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff-check
      args: [custom_components/]
    - id: ruff-format
      args: [custom_components/]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy
      args: [custom_components/]