name: HACS

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          ignore: "brands"
          category: "integration"
