# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run tests
      run: |
        pytest tests
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.12' }}
      run: |
        pytest tests -rxf -x -v -l --cov=./ --cov-report=xml > /dev/null
        coverage report --skip-covered
        curl -sfSL https://codecov.io/bash | bash -
